openapi: 3.0.0
info:
  title: {{title}}
  description: {{description}}
  contact:
    name: {{contact_name}}
    email: {{contact_email}}
    url:  {{contact_website}}
  version: {{version}}

servers:
  - url: /

tags:
  - name: Health
    description: API Health
  - name: Learning

paths:
  /ping:
    get:
      summary: Check the API health
      operationId: wine_predictor_api.services.healthcheck.ping
      tags: [ Health ]
      responses:
        '200':
          description: API is up and running
  
  /wine/model:
    patch:
      summary: (Re)train the wine quality model based on a predefined dataset
      operationId: wine_predictor_api.services.learner.train_model
      tags: [ Learning ]
      responses:
          '200':
            description: New model has been successfully trained but discarded
          '201':
            description: New model has been successfully trained and saved as default
          '404':
            description: Model path is not found
          '500':
            description: Internal server error

